### ISSUE TITLE
local hostta çalışır mı ?

### ISSUE THREAD

**Issue by AltAirFr** [XianThi/c2bot#2]
localde çalıştırabilir miyim ?

**Comment by XianThi** [comment]
If the required php.ini settings are appropriate, it will also work on the localhost. Php functions like fopen, curl, file_get_contents are used. it is still worth checking.

[TR]
gerekli fonksiyonların çalışması için php.ini ayarları uygunsa localde de çalışır. fopen, curl, file_get_contents gibi fonksiyonlar default olarak açık geliyor. yine de kontrol etmekte fayda var.
